= qcacld-2.0 for Qualcomm WIFI module

The qcacld-2.0 is Qualcomm WIFI module out-of-tree driver.

To make and make install module for QCA9377-3 and QCA6174-3:
[source,console]
$: KERNEL_SRC=<your kernel path> CONFIG_CLD_HL_SDIO_CORE=y CONFIG_PER_VDEV_TX_DESC_POOL=1 SAP_AUTH_OFFLOAD=1 \
CONFIG_QCA_LL_TX_FLOW_CT=1 CONFIG_WLAN_FEATURE_FILS=y CONFIG_FEATURE_COEX_PTA_CONFIG_ENABLE=y \
CONFIG_QCA_SUPPORT_TXRX_DRIVER_TCP_DEL_ACK=y CONFIG_WLAN_WAPI_MODE_11AC_DISABLE=y TARGET_BUILD_VARIANT=user \
CONFIG_NON_QC_PLATFORM=y CONFIG_HDD_WLAN_WAIT_TIME=10000 make -j4

[source,console]
$: KERNEL_SRC=<your kernel path> INSTALL_MOD_PATH=<modules> make modules_install

(NOTE: The "modules" directory should be already installed kernel module inside)

If you want to enable P2P device interface you must add this parameter to make command line:
[source,console]
CONFIG_P2P_INTERFACE=y

*Prepare WIFI/BT firmware*

Because of the license restriction, please contact TechNexion FAE or Sales to get licensed firmware files.

After getting the firmware binary:

Decompress the tarball and put all the firmware files into your target's `/lib/firmware` directory.

*Support kernel:* `4.9.x` `4.14.x` `5.4.x`

